<a href="https://colab.research.google.com/github/kiztheflutterer/kiztheflutterer/blob/main/draft1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install Pandas

Requirement already satisfied: Pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from Pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from Pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from Pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from Pandas) (2024.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->Pandas) (1.17.0)

In [ ]:
import numpy as np
import pandas as pd

from pandas import DataFrame

In [ ]:
import numpy as np
import pandas as pd

numbers_df = pd.DataFrame(np.arange(0,90,3).reshape(10,3), index = ['row 1','row 2', 'row 3', 'row 4', 'row 5', 'row 6', 'row 7', 'row 8', 'row 9', 'row 10'], columns= ['column 1', 'column 2', 'column 3'])

In [ ]:
numbers_df

        column 1  column 2  column 3
row 1          0         3         6
row 2          9        12        15
row 3         18        21        24
row 4         27        30        33
row 5         36        39        42
row 6         45        48        51
row 7         54        57        60
row 8         63        66        69
row 9         72        75        78
row 10        81        84        87

In [ ]:
numbers_df.iloc [0,1]

3

In [ ]:
numbers_df.iloc[[2,3,4,5],[1,2]]

       column 2  column 3
row 3        21        24
row 4        30        33
row 5        39        42
row 6        48        51

In [ ]:
mask = numbers_df > 20
mask

        column 1  column 2  column 3
row 1      False     False     False
row 2      False     False     False
row 3      False      True      True
row 4       True      True      True
row 5       True      True      True
row 6       True      True      True
row 7       True      True      True
row 8       True      True      True
row 9       True      True      True
row 10      True      True      True

In [ ]:
numbers_df[mask]

        column 1  column 2  column 3
row 1        NaN       NaN       NaN
row 2        NaN       NaN       NaN
row 3        NaN      21.0      24.0
row 4       27.0      30.0      33.0
row 5       36.0      39.0      42.0
row 6       45.0      48.0      51.0
row 7       54.0      57.0      60.0
row 8       63.0      66.0      69.0
row 9       72.0      75.0      78.0
row 10      81.0      84.0      87.0